### Testing my backend
### ==================
###
### See full help at:
### https://www.jetbrains.com/help/webstorm/http-client-in-product-code-editor.html

### Note: You can directly paste a curl-command => gets automatically converted to an http-request
### and via Context Action, you can create a curl-command from an http-request

### GET all blogs
GET http://localhost:3003/api/blogs

### POST a blog
POST http://localhost:3003/api/blogs/
content-type: application/json

{
  "title": "via REST api",
  "author": "api",
  "url": "me.com",
  "likes": 3
}

### POST a blog
POST http://localhost:3003/api/blogs/
content-type: application/json

{
  "title": "smart stuff",
  "author": "hugo",
  "url": "other-domain.com",
  "likes": 2
}

### POST a blog
POST http://localhost:3003/api/blogs/
content-type: application/json

{
  "title": "newish",
  "author": "who",
  "url": "github.com",
  "likes": 5,
  "id": "630ca495dc3196e7eebc06a5"
}
