### Testing my backend
### ==================
###
### See full help at:
### https://www.jetbrains.com/help/webstorm/http-client-in-product-code-editor.html

### Note: You can directly paste a curl-command => gets automatically converted to an http-request
### and via Context Action, you can create a curl-command from an http-request

### GET all blogs
GET http://localhost:3003/api/blogs

### POST a blog
POST http://localhost:3003/api/blogs/
content-type: application/json

{
  "title": "via REST api",
  "author": "api",
  "url": "me.com",
  "likes": 3
}
