### GET request with a header
GET http://localhost:3003/api/blogs
Accept: application/json

### Send POST request with json body
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "new stuff",
  "author": "hugo",
  "url": "",
  "likes": 2
}
